# Generated by Django 6.0 on 2026-02-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_equipmentcategory_image_alter_equipment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcategory',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
