# Generated by Django 6.0 on 2026-03-16 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_alter_booking_end_date_alter_booking_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="website.equipment",
            ),
        ),
    ]
