# Generated by Django 6.0 on 2026-03-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_equipment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
