# Generated by Django 6.0 on 2026-03-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_equipmentcategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("returned", "Returned"),
                    ("active", "Active"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
