# Generated by Django 6.0 on 2026-04-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_alter_booking_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
